return {
  defaults = {
    align = "center",
    default_label_template = "Monitor $n",
    autodiscover = true,
    fg = "lime",
    clear_on_draw = true,
    pad_y = 1,
    pad_x = 0,
    bg = "gray",
    text_scale = 0.5,
  },
  monitors = {
    {
      name = "monitor_18",
      label = "Sector 7",
      text_scale = 2,
      pad_y = 1,
      bg = "black",
      fg = "red",
    },
    {
      name = "monitor_13",
      fg = "cyan",
      label = "Hostile Neural Networks",
      align = "center",
      pad_y = 1,
      bg = "black",
      text_scale = 1,
    },
    {
      name = "monitor_19",
      label = "Cyanite Production",
      fg = "red",
      text_scale = 2.5,
      bg = "black",
      pad_y = 1,
    },
    {
      name = "monitor_20",
      label = "Cyanite Reactor 1",
      text_scale = 1.5,
      pad_y = 1,
      bg = "cyan",
      fg = "lightBlue",
    },
    {
      name = "monitor_21",
      label = "Cyanite Reactor 2",
      text_scale = 1.5,
      pad_y = 1,
      bg = "cyan",
      fg = "lightBlue",
    },
    {
      name = "monitor_22",
      label = "Cyanite Reactor 3",
      text_scale = 1.5,
      pad_y = 1,
      bg = "cyan",
      fg = "lightBlue",
    },
    {
      name = "monitor_23",
      label = "Cyanite Reactor 4",
      text_scale = 1.5,
      pad_y = 1,
      bg = "cyan",
      fg = "lightBlue",
    },
    {
      name = "monitor_27",
      label = "Fusion Crafting",
      text_scale = 2.5,
      pad_y = 1,
      bg = "orange",
      fg = "black",
    },
    {
      fg = "white",
      name = "monitor_16",
      label = "Welcome to my LABORATORY",
      align = "center",
      text_scale = 1.5,
      bg = "red",
      pad_y = 1,
    },
    {
      name = "monitor_14",
      label = "Base Control",
      text_scale = 3,
      bg = "red",
      fg = "white",
    },
    {
      fg = "white",
      label = "Quantum Autocrafting",
      text_scale = 1.5,
      pad_y = 1,
      bg = "purple",
      name = "monitor_30",
    },
    {
      name = "monitor_33",
      label = "ME Storage Drives",
    },
    {
      name = "monitor_38",
      label = "Authorized Personel ONLY",
    },
    {
      text_scale = 1.5,
      name = "monitor_44",
      label = "Applied Energistics Autocrafting",
    },
    {
      text_scale = 1,
      name = "monitor_45",
      label = "Mekanism Gas Storage",
    },
  },
}